os: osx
osx_image: xcode13.0
language: swift
script: xcodebuild clean build test -project /Users/larissa.ganaha/Desktop/EssentialFeed/EssentialFeed.xcodeproj -scheme "CI" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,OS=15.0,name=iPhone 8"
